### ISSUE TITLE
Cargo install fails

### ISSUE THREAD

**Issue by samvrlewis** [exclave/exclave#19]
Have tried to `cargo install exclave` on two different systems (one Fedora, one Ubuntu), both fail with the same error:

```
error: failed to run custom build command for `exclave v0.2.5`                                                        
process didn't exit successfully: `/tmp/cargo-install2Xyp03/release/build/exclave-f172f548cd3d40f5/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'assertion failed: cmd.status.success()', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/exclave-0.2.5/build.rs:19:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: build_script_build::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
   9: __rust_maybe_catch_panic
  10: std::rt::lang_start_internal
  11: main
  12: __libc_start_main
  13: _start

warning: build failed, waiting for other jobs to finish...
error: failed to compile `exclave v0.2.5`, intermediate artifacts can be found at `/tmp/cargo-install2Xyp03`
```

Building from source appears to work fine. Looking at `build.rs` it appears it's an issue with the git versioning, but my rust isn't good enough to debug any further.

Thanks for the great framework!

**Comment by xobs** [comment]
Thanks for the report, @samvrlewis .  The issue appears to be that "git describe --tags --dirty=-modified" is failing.  Perhaps the arguments to "git" are different on your system.

Can you please tell me the output to `git describe --tags --dirty=-modified`, and also `git --version` on at least one of those systems?

I've made git failures non-fatal as of 7c99b4730317f453aaca0d3ee0581e4ba6d26e60

**Comment by samvrlewis** [comment]
Thanks for the quick response. I think the git output is what is expected, because it works when I works when building from source. Outputs from my git commands below:

```
root@ubuntu:/data/exclave# git describe --tags --dirty=-modified
v0.2.5
root@ubuntu:/data/exclave# git --version
git version 2.7.4
```

However, when running the command in (what I think is the cargo build folder?), I get the following:

```
root@ubuntu:/tmp/cargo-install2Xyp03/release/build/exclave-f172f548cd3d40f5# git describe --tags --dirty=-modified
fatal: Not a git repository (or any parent up to mount point /tmp)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Indeed, stracing the build script, it seems to get the same thing.

```
root@ubuntu:/tmp/cargo-install2Xyp03/release/build/exclave-f172f548cd3d40f5# strace ./build-script-build  2>&1 | grep git -B 5 -A 5
close(5)                                = 0
close(7)                                = 0
ioctl(4, FIONBIO, [1])                  = 0
ioctl(6, FIONBIO, [1])                  = 0
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}], 2, -1) = 1 ([{fd=6, revents=POLLIN}])
read(6, "fatal: Not a git repository (or ", 32) = 32
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=12425, si_uid=0, si_status=128, si_utime=0, si_stime=0} ---
read(6, "any parent up to mount point /tm", 32) = 32
read(6, "p)\nStopping at filesystem bounda"..., 64) = 64
read(6, "TEM not set).\n", 128)         = 14
read(6, "", 114)
```

Again, not familiar enough with rust but maybe is it a wrong assumption that if the `git` command works it means you're building from source? Looks as though Cargo isn't getting the git metadata when building exclave, I guess? Is this maybe an issue with the version of Cargo I'm using? I'm using cargo 1.30.0.

**Comment by xobs** [comment]
Ah, I see the issue -- if you download the zip, or if cargo moves the source somewhere, or the source is somehow moved somewhere else without the `.git` folder, or you're building with "cargo install", then of course `git describe --tags` will fail.

The patch that I made is therefore the correct solution, because it'll try to use git to show version information, but won't fail if git isn't available.

**Comment by xobs** [comment]
Thanks again for researching this!  If the latest commit solves the problem, can you please close this issue?

**Comment by samvrlewis** [comment]
Awesome - thanks, I'm stilling getting v0.2.5 when I run cargo install, does it take a while for the package to get pushed to crates.io? Have tried deleting ~/.cargo but that didn't seem to help.

**Comment by xobs** [comment]
Can you try again?  The rebuild took a while.

**Comment by samvrlewis** [comment]
Hmm, I'm still getting v0.2.5 - it shows that as the latest version on crates.io too - https://crates.io/crates/exclave

**Comment by xobs** [comment]
I'm sorry, I was having trouble pushing the repo.  The page now shows 0.2.6.

**Comment by sam-bristow** [comment]
I was able to successfully install the new version via Cargo just now.

Fedora 29
cargo 1.32.0
exclave 0.2.6

**Comment by xobs** [comment]
Thanks for checking, @sam-bristow .  I'll close this issue now.  If you still experience problems, please let me know!

**Comment by samvrlewis** [comment]
Thanks @xobs, works for me now too!
