### ISSUE TITLE
Fail scenario on first test fail

### ISSUE THREAD

**Issue by samvrlewis** [exclave/exclave#20]
In my test jig, I'd like the tests to stop as soon as any individual test fails. At the moment, tests that don't have dependencies on the failed test will still continue to run. I'd like to do this so that production isn't slowed running all test on a faulty board and so the faulty board can be examined ASAP. 

As far as I can tell there isn't currently a nice way of doing this, without making every test depend on the test that runs before it.

I would be happy to take a shot on implementing this - I was thinking to add a `StopOnFirstFailure` config option in the `Scenario` unit but happy to hear thoughts on whether this is useful or if there's a better way of doing what I want.

Thanks again for the great framework!

**Comment by xobs** [comment]
How about adding a `StopAfterFailureCount` flag?  It may be that a few errors are acceptable for a particular product, where you can mark it as bad and have a technician rework it.  Other times you may want to stop on the first failure, as you are looking to do.

**Comment by sam-bristow** [comment]
A similar but slightly different feature I would find useful is a way to mark a Test as a requirement for every other downstream Test.

Maybe an `OnFailure=abort` option in the Test definition?

The particular use case I've found is when I have some early sanity check tests, ike checking power rails on the DUT.
