### ISSUE TITLE
Need proper open source license

### ISSUE THREAD

**Issue by ssfivy** [exclave/exclave#3]
Exclave currently is not under a specific license.
According to [this article](https://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github) this means all right reserved and the licensing terms are unknown.
Suggest adding a license to make this clear.

**Comment by xobs** [comment]
The Cargo.toml file specified that it was licensed under the BSD 3-Clause license, however that was not made explicit.  The inclusion of a LICENSE file now should address this issue.
